# -*- coding: utf-8 -*-
"""Flaviana Gomes - 232_EntradaSaida_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCfdZia7_KtNE_HS-K5lCaGMM7ZIGVOy

# Exercícios para construir programas com ENTRADA, PROCESSAMENTO e SAÍDA

### 1. Faça um programa que leia um número, multiplique ele por 2 e apresente o resultado.
      LEIA numero
      resultado = numero * 2
      ESCREVA resultado
"""

# 1º passo - identificar a(s) entrada(s) - variável número
print('*** PROGRAMA PARA MULTIPLICAR UM NÚMERO POR DOIS***')
numero = int(input('Informe um valor......: '))

# 2º passo - identificar o processamento/cálculo
resultado = numero * 2

# 3º passo - apresentar a(s) variáveis que foram calculadas
print('A multiplicação é=',resultado)

"""### 2. Faça um programa que:
* receba três números inteiros
* calcule e mostre a soma desses números.

"""

# Entrada
numero1 = int(input("Digite um número: "))
numero2 = int(input("Digite um número: "))
numero3 = int(input("Digite um número: " ))
 # Processamento/cálculo
soma_dos_numeros = numero1 + numero2 + numero3
 # Saída
print('O resultado da soma é',soma_dos_numeros)

"""### 3. Faça um programa que receba três notas, calcule e mostre a média aritmética.     """

nota1 = int(input("Digite a nota 1: "))
nota2 = int(input("Digite a nota 2: "))
nota3 = int(input("Digite a nota 3: "))
media_aritmetica = ((nota1 + nota2 + nota3)/3)
print(f'A média aritmética é {media_aritmetica:.2f}')

"""### 4. Faça um programa que:
* receba o salário de um funcionário
* calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%.

      LEIA salario
      novoSalario = salario + (salario * 25 / 100)
      ESCREVA novoSalario
"""

print("Programa para calcular aumento de 25% do salário")
salario = float(input("Digite o seu salário: "))
novoSalario = salario + (salario * 25/100)
print(f"O novo salário é R$ {novoSalario:.2f} e estou contente")

"""### 5. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário.

"""

print('.'*100)
print("Faça o cálculo para descobrir seu nome salário")
print('.'*100, '\n')
salario = float(input ("Digite aqui o seu salário atual: "))
percentual = float(input ("Digite aqui o percentual do aumento: "))
aumento = salario + (salario * percentual / 100)
print(f"Valor do novo salário: R$ {aumento:.2f}")

"""### 6. Faça um programa que receba o salário base de um funcionário, calcule e mostre o salário a receber, sabendo-se que o funcionário tem gratificação de 5% sobre o salário base e **paga imposto** de 7% também sobre o salário base."""

print('.'*150, '\n')
print("VAMOS CALCULAR O SEU NOVO SALÁRIO")
print('.'*150, '\n')
salario = float(input("Digite o seu salário atual:"))
gratificacao = salario * (5/100)
imposto = salario * (7/100)
novoSalario = salario + gratificacao + imposto
print(f'Novo salário é R$ {novoSalario:.2f}. Parabéns!')

"""### 7. Faça um programa que receba o salário base de um funcionário, calcule e mostre seu salário a receber, sabendo-se que o funcionário tem gratificação de 50,00 sobre o salário base e **paga** imposto que deve ser lido e é aplicado sobre o salário base.

    LEIA salario, perImposto
    imposto = salario * perImposto / 100
    salario_a_receber = salario + 50 - imposto
    ESCREVA salario_a_receber
"""

print('.'*100)
print("Você tem uma gratificação de 50 reais. Calcule o seu novo salário a partir dela e do percentual do imposto")
print('.'*100)
salario = float(input("Digite o valor do salário: "))
perImposto = float(input("Qual é o percentual do imposto? "))
gratificacao = 50
imposto = (salario * (perImposto/ 100))
salario_a_receber = salario + gratificacao - imposto
print (f'O novo salário é R$ {salario_a_receber:.2f}')

"""### 8. Faça um programa que receba o valor de um depósito e o valor da taxa de juros, calcule e mostre o valor do rendimento e o valor total depois do rendimento de um mês.
    rendimento = deposito * taxa / 100
    total = deposito + rendimento
"""

print("Calcule o rendimento:")
deposito = float(input("Digite o valor do depósito: "))
taxa = float(input("Digite o valor da taxa: "))
rendimento = deposito * taxa / 100
print(f"Seu rendimento é R$ {rendimento:.2f}")

"""### 9. Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: Área = (base * altura) / 2."""

print("OLÁ, MUNDO! VAMOS CALCULAR A ÁREA DE UM TRIÂNGULO?")
base = int(input("Coloque o valor da base: "))
altura = int(input("Coloque o valor da altura: "))
area = base * altura / 2
print("AQUI ESTÁ O SEU RESULTADO: ",area)

"""### 10. Faça um programa que calcule e mostre a área de um círculo. Sabe-se que:
    area = pi * raio²
    Como pi é um valor que conhecemos, então use a seguinte fórmula:
    area = 3.1415 * raio²
"""

print("Vamos calcular a área de um círculo? Para isso, vamos calcular o pi multiplicado pelo raio²")
pi = 3.1415
raio = float(input("Digite o valor do raio²: "))
area = pi * raio ** 2
print(f"O valor da área é {area:.3f} metros quadrados")

"""### 11. Faça um programa que receba um número, calcule e mostre:
* O número digitado ao quadrado
* O número digitado ao cubo
* A raiz do número digitado
* A raiz cúbica do número digitado

      LEIA numero
      quadrado = numero ** 2
      cubo = numero ** 3
      raiz_quadrada = numero ** (½) (meio, ou 0.5)
      raiz_cubica = numero ** (⅓) (um terço, ou 0.33)
      ESCREVA quadrado, cubo, raiz_quadrada, raiz_cubica


      raiz_quadrada = numero ** (1/2) ou
      raiz_quadrada = numero ** 0.5
"""

print("Vamos fazer algumas operações com um mesmo número?")
numero = int(input("Digite o seu número: "))
quadrado = numero ** 2
cubo = numero ** 3
raiz_quadrada = numero ** 0.5
raiz_cubica = numero ** 0.33
print("O número ao quadrado é:", quadrado)
print("O número ao cubo é:", cubo)
print(f"A raiz quadrada do número é: {raiz_quadrada:.2f}")
print(f"A raiz cúbica do número é: {raiz_cubica:.2f}")

"""### 12. Faça um programa que receba dois números, calcule e mostre um elevado ao outro. Use os caracteres **

"""

numero_1 = int(input("Digite o número 1: "))
numero_2 = int(input("Digite o número 2: "))
elevado = numero_1 ** numero_2
print("O resultado é:",elevado)

"""### 13. Sabe-se que:

* pé = 12 polegadas
* 1 jarda = 3 pés
* 1 milha = 1760 jarda

Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.

* Polegadas;
* Jardas;
* Milhas.

      LEIA pes
      polegadas = pes * 12
      jardas = pes / 3
      milhas = jardas / 1760
      ESCREVA polegadas, jardas, milhas
"""

pes = int(input("Digite o número de pés: "))
polegadas = pes * 12
jardas = pes / 3
milhas = jardas / 1760
print(f"O número de polegadas é:{polegadas:.2f}")
print(f"O número de jardas é:{jardas:.2f}")
print(f"O número de milhas é:{milhas:.2f}")

"""### 14. Faça um programa que receba o ano de nascimento de uma pessoa e o ano atual, calcule e mostre:
* a idade atual da pessoa;
* quantos anos ela terá em 2050.
"""

ano_nascimento = int(input("Qual o ano do seu nascimento? "))
idade_atual = 2023 - ano_nascimento
idade_futura = 2050 - ano_nascimento
print("Sua idade atual é",idade_atual)
print("Em 2050 você terá:", idade_futura)

"""#### 15. O custo ao consumidor de um carro novo é a soma do preço de fábrica com o percentual de lucro do distribuidor e dos impostos aplicados ao preço de fábrica. Faça um programa que receba o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:
* o valor correspondente ao lucro do distribuidor;
* o valor correspondente aos impostos;
* o preço final do veículo.
        LEIA preco_fabrica
        LEIA percentual_lucro_distribuidor
        LEIA percentual_imposto
        lucro_distribuidor = preco_fabrica * percentual_lucro_distribuidor / 100
        valor_imposto = preco_fabrica * percentual_imposto / 100
        preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
        ESCREVA lucro_distribuidor
        ESCREVA valor_imposto
        ESCREVA preco_final

"""

preco_fabrica = int(input("Digite o valor do preço de fábrica: "))
percentual_lucro = int(input("Digite o valor do lucro: "))
percentual_imposto = int(input("Digite o percentual do imposto: "))
lucro_distribuidor = preco_fabrica * percentual_lucro / 100
valor_imposto = preco_fabrica * percentual_imposto / 100
preco_final = preco_fabrica + lucro_distribuidor + valor_imposto
print("O lucro do distribuidor é:",lucro_distribuidor)
print("O valor do imposto é:",valor_imposto)
print("O preço final é:",preco_final)

"""### 16. Faça um programa que receba o número de horas trabalhadas e o valor do salário mínimo, calcule e mostre o salário a receber, seguindo estas regras:
* a hora trabalhada vale a metade do salário mínimo.
* o salário bruto equivale ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
* o imposto equivale a 3% do salário bruto.
* o salário a receber equivale ao salário bruto menos o imposto.
      LEIA qtde_horas_trabalhadas
      LEIA valor_salario_minimo
      valor_hora_trabalhada = valor_salario_minimo / 2
      valor_salario_bruto = valor_hora_trabalhada * qtde_horas_trabalhadas
      imposto = valor_salario_bruto * 3 / 100
      valor_salario_liquido =  valor_salario_bruto - imposto
      ESCREVA valor_salario_liquido
"""

qtde_horas_trabalhadas = float(input("Digite a quantidade de horas trabalhadas no dia: "))
valor_salario_minimo = float(input("Digite o valor do salário mínimo: "))
hora_trabalhada = valor_salario_minimo / 2
salario_bruto = hora_trabalhada * qtde_horas_trabalhadas
imposto = salario_bruto * 3 / 100
salario_liquido = salario_bruto - imposto
print(f"O salário líquido é: R${salario_liquido:.2f}")

"""### 17. Um trabalhador recebeu seu salário e o depositou em sua conta bancária. Esse trabalhador emitiu dois cheques e agora deseja saber seu saldo atual. O banco criou uma taxa para a operação bancária de retirada que tem que pagar um imposto de 0.38% e o saldo inicial da conta está zerado.

      LEIA salario
      LEIA valor_cheque1
      LEIA valor_cheque2
      imposto_cheque1 = valor_cheque1 * 0.38 / 100
      saque1 = valor_cheque1 + imposto_cheque1
      imposto_cheque2 = valor_cheque2 * 0.38 / 100
      saque2 = valor_cheque2 + imposto_cheque2
      saldo = salario - saque1 - saque2
      ESCREVA saldo

"""

print('.'*100)
print("Calcule o seu saldo atual")
print('.'*100)
salario = float(input("Digite o valor do salário: "))
cheque1 = float(input("Qual o valor do primeiro cheque? "))
cheque2 = float(input("Qual o valor do segundo cheque? "))
imposto_cheque1 = cheque1 * 0.38 / 100
saque1 = cheque1 + imposto_cheque1
imposto_cheque2 = cheque2 * 0.38 / 100
saque2 = cheque2 + imposto_cheque2
saldo = salario - saque1 - saque2
print(f"O seu saldo atual é R$ {saldo:.2f}")

"""### 18. Faça um programa que receba a medida do ângulo (em graus) formado por uma escada apoiada no chão e encostada na parede e a altura da parede onde está a ponta da escada. Calcule e mostre a medida dessa escada. Observação: as funções trigonométricas implementadas nas linguagens de programação trabalham com medidas de ângulos em radianos.
      LEIA angulo
      LEIA altura
      import math # carrega a biblioteca matemática
      radiano = angulo * math.pi / 180
      escada = altura / math.sin(radiano)
      ESCREVA escada
**Observação**: Para usar seno em Python, deve-se usar esta linha de código **import math** e esta, no cálculo, **math.sin(numero)**

**import math**

escada = altura / **math.sin**(numero)
"""

import math
# import chama a biblioteca matemática e disponibiliza ao programa, várias
# funções prontas, basta usá-las quando necessário.
# Segue alguns exemplos:
print('Seno',math.sin(90) )
print('Cosseno',math.cos(100) )
print('Potência',math.pow(2,8))
print('Raiz quadrada',math.sqrt(24))
math.pi

print("Há uma escada encostada na parede em que precisamos descobrir a medida dela")
angulo = float(input("Coloque aqui o ângulo em graus: "))
altura = float(input("Agora digite a altura: "))
import math
radiano = angulo * (math.pi / 180)
escada = altura / (math.sin(radiano))
print(f"A medida da escada é: {escada:.2f}")

"""###19. Sabe-se que o quilowatt de energia custa um quinto do salário mínimo. Faça um programa que receba o valor do salário mínimo e a quantidade de quilowatts consumida por uma residência. Calcule e mostre:


* o valor de cada quilowatt;
* o valor a ser pago por essa residência;
* o valor a ser pago com desconto de 15%.
      LEIA valor_salario
      LEIA qtde_quilowatt
      valor_quilowatt = valor_salario / 5
      valor_em_reais = valor_quilowatt * qtde_quilowatt
      valor_descontado = valor_em_reais * 15 / 100
      valor_com_desconto =  valor_em_reais − valor_descontado
      ESCREVA valor_quilowatt
      ESCREVA valor_em_reais
      ESCREVA valor_com_desconto

"""

print("Quantos quilowatts são consumidos na residência?")
valor_salario = float(input("Qual o valor do salário mínimo? "))
qtde_quilowatt = float(input("Quantos quilowatts foram gastos? "))
valor_quilowatt = valor_salario / 5
valor_em_reais = valor_quilowatt * qtde_quilowatt
valor_descontado = valor_em_reais * 15 / 100
valor_com_desconto = valor_em_reais - valor_descontado
print(f"O valor dos quilowatts é R$ {valor_quilowatt:.2f}")
print(f"O valor em reais é R$ {valor_em_reais:.2f}")
print(f"O valor com desconto é R$ {valor_com_desconto:.2f}")

"""### 20. Faça um programa que receba um número real, encontre e mostre:

* a parte inteira desse número;
* a parte fracionária desse número;
* o arredondamento desse número.

      LEIA numero
      parte_inteira = numero // 1
      parte_fracionaria = numero - parte_inteira
      numero_arredondado = round (numero)
      ESCREVA parte_inteira
      ESCREVA parte_fracionaria
      ESCREVA numero_arredondado
      
**Observação**: Para arredondar um número em Python, usa-se a função **round(numero)**, onde se o número real/float estiver em igual distância entre o inteiro de cima e o inteiro de baixo, esta função arredonda para o número mais próximo.


"""

print("Vamos trabalhar com um número decimal")
numero = float(input("Digite aqui o seu número: "))
parte_inteira = numero // 1
parte_fracionaria = numero - parte_inteira
numero_arredondado = round (numero)
print("Essa é a parte inteira:",parte_inteira)
print(f"A parte fraconaria é {parte_fracionaria:.2f}")
print("E esse é número arrendondado:", numero_arredondado)

"""### 21. Faça um programa que receba uma hora formada por hora e minutos (um número real), calcule e mostre a hora digitada apenas em minutos. Lembre-se de que:
* para quatro e meia, deve-se digitar 4.30;
* os minutos vão de 0 a 59.
      LEIA hora
      h = pegar a parte inteira da variável hora
      minutos = hora − h
      conversao = (h * 60) + (minutos * 100)
      ESCREVA conversao

"""

hora = float(input("Digite aqui a hora: "))
h = hora // 1
minutos = hora - h
conversao = (h * 60) + (minutos * 100)
print("A hora em minutos é:",conversao)

"""### 22. Faça um programa que receba o custo de um espetáculo teatral e o preço do convite desse espetáculo. Esse programa deverá calcular e mostrar a quantidade de convites que devem ser vendidos para que, pelo menos, o custo do espetáculo seja alcançado.

"""

espetaculo = float(input("Digite aqui o custo do espetáculo: "))
preco_do_convite = int(input("Digite aqui o preço do convite: "))
numero_de_convites = espetaculo / preco_do_convite
print("A quantidade de convites a ser vendida é:",round (numero_de_convites))