# -*- coding: utf-8 -*-
"""Flaviana Gomes - 232_Est_Dec_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jitm4VAXRXPAVerGT_G9YOMFyYGue1EZ

#Lista de exercícios de ESTRUTURA de DECISÃO (estrutura condicional)
#Fazer do 1 ao 20, o restante fica para estudos

### 1.a) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%.
"""

# entrada
salario = float(input('Digite o salário '))
# processamento
if salario <= 500:
    novo = salario + (salario * 50 / 100)
    # saída
    print(f'Novo salário {novo:.2f}')

"""###1.b) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%; Salários maiores que 500, reajuste de 30%."""

salario = float(input('Cadastre um salário '))
if salario <= 500:
  novo = salario + salario * 50 / 100
  print (f'Novo salário R$ {novo:.2f}')
else:
   novo = salario + salario * 30 / 100
   print (f'Novo salário R$ {novo:.2f}')

"""###1.c) Faça um algoritmo que calcule e exiba o salário reajustado de um funcionário de acordo com a seguinte regra: Salário até 500, reajuste de 50%; Salários maiores que 500 e até 1000, reajuste de 30%; Salários acima de 1000, reajuste de 10%."""

salario = float(input('Cadastre um salário '))
if salario <= 500:
  novo = salario + salario * 50 / 100
  print (f'Novo salário R$ {novo:.2f}')
elif salario > 500 and salario <= 1000:
    novo = salario + salario * 30 / 100
    print ('Novo salário R$ {novo:.2f}')
else:
   novo = salario + salario * 10 / 100
   print (f'Novo salário R$ {novo:.2f}')

salario = float(input('Cadastre um salário '))
if salario <= 500:
  novo = salario + salario * 50 / 100
elif salario > 500 and salario <= 1000:
    novo = salario + salario * 30 / 100
else:
   novo = salario + salario * 10 / 100
print (f'Novo salário é R$ {novo:.2f}')

"""###2. Faça um algoritmo que leia o nome e a idade de uma pessoa, verifique se a idade de uma pessoa é menor ou maior de idade. Considera-se maior de idade uma pessoa com 18 anos ou mais. Como saída o algoritmo deve informar o nome e a idade da pessoa e depois uma mensagem se ela é ou não maior de idade.

"""

nome = str(input('Qual o seu nome? '))
idade = int(input('Qual a sua idade? '))
if idade >= 18:
    print('Seu nome é',nome,', sua idade é',idade,'e você é maior de idade')
else:
    print(f'{nome}, tem {idade} anos e você é menor de idade')

"""###3.a) Faça um algoritmo que leia duas notas de um aluno, calcule a média e verifique, apresentando, se está aprovado ou reprovado."""

P1 = float(input('Qual é a nota da P1? '))
P2 = float(input('Qual é a nota da P2? '))
media = (P1 + P2) / 2
if media >= 6:
    print('Sua média é',media, 'e você foi aprovado')
else:
    print(f'Sua média é {media} e você foi reprovado')

"""###3.b) Faça um algoritmo que calcule e apresente o que foi requerido no exercício 3.a) e também avalie a condição de aprovar/reprovar, apenas quando o aluno tem frequencia acima de 75%, este valor deve ser lido."""

P1 = float(input('Qual é a nota da P1? '))
P2 = float(input('Qual é a nota da P2? '))
frequencia = float(input('Digite a frequência '))
media = (P1 + P2) / 2
if media >= 6 and frequencia >=75:
    print('Sua média é',media, 'e você foi aprovado')
else:
    print(f'Sua média é {media} e você foi reprovado')

"""###4. Faça um algoritmo que leia o gênero de uma pessoa. Se for digitado M ou F, apresentar 'Gênero válido!'. Caso contrário, 'Gênero inválido!'."""

genero = str(input("Digite o seu gênero: "))
if genero == "M" or genero == "F":
    print("Gênero válido")
else:
    print("Gênero inválido")

"""###5. Tendo como dados de entrada a altura e o gênero (M/F) de uma pessoa (M-masculino ou F-feminino), construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
masculino: (72.7 * altura) - 58;

feminino: (62.1 * altura) - 44.7


"""

altura = float(input('Digite a sua altura '))
genero = input('Digite o seu gênero ')
if genero == "M":
    masculino = (72.7 * altura) - 58
    print (f"Seu peso ideal é {masculino:.2f}")
else:
    feminino = (62.1 * altura) - 44.7
    print(f"Seu peso ideal é {feminino:.2f}")

"""###6. Faça um algoritmo que leia dois números inteiros e mostre o resultado da **diferença** do maior valor pelo menor."""

numero1 = int(input("Digite um número inteiro: "))
numero2 = int(input("Digite outro número inteiro: "))
if numero1 >= numero2:
    conta1 = numero1 - numero2
    print("A diferença entre os dois números é: ", conta1)
else:
    conta2 = numero2 - numero1
    print("A diferença entre os dois números é: ", conta2)

numero1 = int(input("Digite o primeiro número real: "))
numero2= int(input("Digite o segundo número real: "))
if numero1 > numero2:
    conta1 = numero1 - numero2
    print("A diferença entre eles é",conta1)
else:
    conta2 = numero2 - numero1
    print("A diferença entre eles é",conta2)

"""###7. Uma faculdade faz o pagamento de seus professores por hora/aula. Faça um algoritmo que receba o nível e a quantidade de hora/aula, calcule e exiba o salário de um professor e a frase a seguira tabela abaixo:
Professor Nível 1 - 11,00 reais por hora/aula, salário: ...

Professor Nível 2 - 15,00 reais por hora/aula, salário: ...

Professor Nível 3 - 19,00 reais por hora/aula, salário: ...
"""

nivel = int(input("Digite o nível do professor: "))
horas_aula = float(input("Digite a quantidade de horas trabalhadas: "))
if nivel == 1:
    salario = horas_aula * 11
    print("Seu nível é",nivel,"e seu salário é", salario)
elif nivel == 2:
    salario = horas_aula * 15
    print("Seu nível é", nivel,"e seu salário é", salario)
elif nivel == 3:
    salario = horas_aula * 19
    print("Seu nível é", nivel,"e seu salário é", salario)
else:
    print("Nível não cadastrado")

nivel = int(input("Digite o nível do professor: "))
horas_aula = float(input("Digite a quantidade de horas trabalhadas: "))
if nivel == 1:
    taxa_por_hora = 11.00
elif nivel == 2:
    taxa_por_hora = 15.00
elif nivel == 3:
    taxa_por_hora = 19.00
else:
    print("Nível de professor inválido. Escolha 1, 2 ou 3.")
salario = horas_aula * taxa_por_hora
print("Seu nível é:", nivel)
print(f"Seu salário é {salario:.2f}")

"""###8. Faça um algoritmo que leia um número inteiro e mostre uma mensagem indicando se este número é par ou ímpar e se é positivo ou negativo.

"""

numero = int(input("Digite um número inteiro: "))
if numero % 2 == 0 and numero > 0:
    print("Par e Positivo")
elif numero % 2 != 0 and numero > 0:
    print("Ímpar e Positivo")
elif numero % 2 == 0 and numero < 0:
    print("Par e Negativo")
elif numero % 2 != 0 and numero < 0:
    print("Ímpar e Negativo")
else:
    print("Inválido")

numero = int(input("Digite um número inteiro: "))
if numero % 2 == 0:
    par_impar = "par"
else:
    par_impar = "ímpar"

if numero > 0:
    positivo_negativo = "positivo"
elif numero < 0:
    positivo_negativo = "negativo"
else:
    positivo_negativo = "zero"
print(f"O número {numero} é {par_impar} e {positivo_negativo}.")

"""###9. Num determinado Estado, para transferências de veículos, o DETRAN cobra uma taxa de 1% para carros fabricados antes de 1990 e uma taxa de 1.5% para os fabricados de 1990 em diante, taxa esta incidindo sobre o valor de tabela do carro. Faça um algoritmo que leia o ano e o preço do carro, calcule e apresente o imposto a ser pago."""

ano = int(input("Digite o ano de fabricação do carro: "))
preco = float(input("Digite o preço do carro: "))

if ano < 1990:
    taxa = 0.01
else:
    taxa = 0.015

imposto = preco * taxa
print(f"O imposto a ser pago é de R$ {imposto:.2f}")

"""###10. Elabore um algoritmo que informando a idade de um nadador o mesmo terá condições de classificar em uma das seguintes categorias:
infantil = 5 - 10 anos;

juvenil = 11-17 anos;

adulto = maiores de 18 anos.


"""

idade = int(input("Digite a idade: "))

if idade >= 5 and  idade <= 10:
	print("Voce é da categoria Infantil")
elif idade >=11 and idade <=17:
	print("Voce é da categoria Juvenil")
else:
    print("Voce é da categoria Adulto")

"""###11. Um banco concederá um crédito especial aos seus clientes, variável com o saldo médio no último ano. Faça um algoritmo que leia o saldo médio de um cliente e calcule o valor do crédito de acordo com a tabela a seguir. Mostre uma mensagem informando o saldo médio e o valor do crédito.
        Saldo médio
        * de 0 a 200 nenhum crédito
        * de 201 a  400 20% do valor do saldo médio
        * de 401 a  600 30% do valor do saldo médio
        * acima de 601 40% do valor do saldo médio

"""

saldo_medio = float(input("Digite o saldo médio do cliente: "))
if saldo_medio <= 200:
    valor_credito = 0
elif saldo_medio <= 400:
    valor_credito = saldo_medio * 0.20
elif saldo_medio <= 600:
    valor_credito = saldo_medio * 0.30
else:
    valor_credito = saldo_medio * 0.40
print(f"O saldo médio é de R${saldo_medio:.2f}")
print(f"Portanto, o valor do crédito é de R${valor_credito:.2f}")

"""###12. A Organização Mundial de Saúde usa a seguinte tabela para determinar a condição de um adulto, para isso desenvolva um algoritmo para calcular o Índice de Massa Corporal (IMC) e apresenta-lo, dado pela fórmula:
    IMC = peso / (altura)2   (o número 2 significa, elevado ao quadrado)

CONDIÇÃO |  IMC em adultos |
 ---|---
Abaixo do peso  |	Abaixo de 18.5  |
No peso normal	|	Entre 18.5 e 25|
Acima do peso	|	Entre 25.1 e 30|
Obeso		    |	Acima de 30|
"""

print('.'*100)
print("Programa para calcular o Índice de Massa Corporal")
print('.'*100)
peso = float(input("Digite o seu peso: "))
altura = float(input("Digite a sua altura: "))
IMC = peso / (altura ** 2)
if IMC < 18.5:
    print(f"Seu IMC é {IMC:.2f} e, de acordo com ele, você está abaixo do peso.")
elif IMC >= 18.5 and IMC <= 25:
    print(f"Seu IMC é {IMC:.2f} e, de acordo com ele, você está no peso normal.")
elif IMC >=25.1 and IMC <= 30:
    print(f"Seu IMC é {IMC:.2f} e, de acordo com ele, você está acima do peso.")
else:
    print(f"Seu IMC é {IMC:.2f} e, de acordo com ele, você está obeso.")

"""###13. A nota final de um estudante é calculada a partir de três notas atribuídas, respectivamente, a um trabalho de laboratório, a uma avaliação semestral e a um exame final. A média das três notas mencionadas obedece aos pesos a seguir:

 NOTA |  PESO |
 ---|---
Trabalho de laboratório  |   2   |
Avaliação semestral      |   3   |
Exame final              |   5   |

### Faça um programa que receba as três notas, calcule e mostre a média ponderada e o conceito que segue a tabela

MÉDIA PONDERADA    | CONCEITO|
---|---
8,0 <= média <= 10  |    A
7,0 <= média < 8,0  |    B
6,0 <= média < 7,0  |    C
5,0 <= média < 6,0  |    D
 0,0 <= média < 5,0  |    E
       
media_ponderada = (nota_traballho * 2 + avaliacao_semestral * 3 + exame_final * 5) / 10


"""

print('.'*100)
print("Programa para calcular a nota final")
print('.'*100)
lab = float(input("Digite a sua nota do Trabalho de Laboratório: "))
semest = float(input("Digite a sua nota da Avaliação Semestral: "))
exame = float(input("Digite a sua nota do Exame Final: "))
media_ponderada = (lab * 2 + semest * 3 + exame * 5) / 10
if media_ponderada >= 8.0 and media_ponderada <=10:
    print(f"Sua média é {media_ponderada:.2f} e você está dentro do conceito A.")
elif media_ponderada >= 7.0 and media_ponderada < 8.0:
    print(f"Sua média é {media_ponderada:.2f} e você está dentro do conceito B.")
elif media_ponderada >=6.0 and media_ponderada < 7.0:
    print(f"Sua média é {media_ponderada:.2f} e você est1á dentro do conceito C.")
elif media_ponderada >= 5.0 and media_ponderada < 6.0:
    print(f"Sua média é {media_ponderada:.2f} e você está dentro do conceito D.")
else:
    print(f"Sua média é {media_ponderada:.2f} e você está dentro do conceito E.")

"""### 14. Faça um programa que receba três notas de um aluno, calcule e mostre a média aritmética e a mensagem constante na tabela a seguir. Aos alunos que ficaram para exame, calcule e mostre a nota que deverão tirar para serem aprovados, considerando que a média exigida é 6,0.

**Observação**: Esta condição de reprovado e exame, não representa a realidade da faculdade.

MÉDIA ARITMÉTICA | MENSAGEM
    ---|---
    0 <= média < 3 |Reprovado
    3 <= média < 6|Exame
    6 <= média <= 10|Aprovado

```
SE media >= 3 E media < 6
    ESCREVA “Exame”
    nota_exame = 12 - media
    ESCREVA “Você deve tirar a nota”, nota_exame, “para ser aprovado.”

"""

print('.'*100)
print("Programa para calcular a nota final")
print('.'*100)
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
media = (nota1 + nota2 + nota3) / 3

"""### 15. Faça um programa que receba dois números e mostre o maior.

"""

print('.'*100)
print("Programa para revelar o maior número")
print('.'*100)
numero1 = int(input("Digite um número inteiro: "))
numero2 = int(input("Digite agora outro número inteiro: "))
if numero1 > numero2:
    print("O maior número digitado foi", numero1)
else:
    print("O maior número digitado foi", numero2)

"""### 16. Faça um programa que receba três números e mostre-os em ordem crescente. Suponha que o usuário digitará três números diferentes.

```
SE numero1 < numero2 E numero1 < numero3
    SE numero2 < numero3
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero2,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero1,“-”,numero3,“-”,numero2
SE numero2 < numero1 E numero2 < numero3
    SE numero1 < numero3
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero1,“-”,numero3
    SENÃO
        ESCREVA “A ordem crescente é: “,numero2,“-”,numero3,“-”,numero1
SE numero3 < numero1 E numero3 < num2
    SE numero1 < numero2
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero1,“-”,numero2
    SENÃO
        ESCREVA “A ordem crescente é: “,numero3,“-”,numero2,“-”,numero1
  ```
"""

numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))
numero3 = float(input("Digite o terceiro número: "))

if numero1 < numero2 and numero1 < numero3:
    if numero2 < numero3:
        print(f"A ordem crescente é: {numero1} - {numero2} - {numero3}")
    else:
        print(f"A ordem crescente é: {numero1} - {numero3} - {numero2}")
elif numero2 < numero1 and numero2 < numero3:
    if numero1 < numero3:
        print(f"A ordem crescente é: {numero2} - {numero1} - {numero3}")
    else:
        print(f"A ordem crescente é: {numero2} - {numero3} - {numero1}")
elif numero3 < numero1 and numero3 < numero2:
    if numero1 < numero2:
        print(f"A ordem crescente é: {numero3} - {numero1} - {numero2}")
    else:
        print(f"A ordem crescente é: {numero3} - {numero2} - {numero1}")

"""### 17. Faça um programa que receba três números obrigatoriamente em ordem crescente e um quarto número que não siga essa regra. Mostre, em seguida, os quatro números em ordem decrescente. Suponha que o usuário digitará quatro números diferentes.

```code
SE numero4 > numero3
    ESCREVA “A ordem decrescente é: “,numero4,“-”,numero3,“-”,numero2,“-”,numero1
SENÃO SE numero4 > numero2 E numero4 < numero3
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero4,“-”,numero2,“-”,numero1
SENÃO SE numero4 > numero1 E numero4 < numero2
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero4, “-”,numero1
SENÃO SE numero4 < numero1
    ESCREVA “A ordem decrescente é: “,numero3,“-”,numero2,“-”,numero1,“-”,numero4
```
"""

numero1 = float(input('Digite o numero1: '))
numero2 = float(input('Digite o segundo numero: '))
numero3 = float(input('Digite o terceiro numero: '))
numero4 = float(input('digite o quarto numero: '))
if numero4 > numero3:
    print(f'A ordem decrescente é: {numero4} - {numero3} - {numero2} - {numero1}')
elif numero4 > numero2 and numero4 < numero3:
    print(f'A ordem decrescente é: {numero3} - {numero4} - {numero2} - {numero1}')
elif numero4 > numero1 and numero4 < numero2:
    print(f'A ordem decrescente é: {numero3} - {numero2} - {numero4} - {numero1}')
else:
    numero4 < numero1
    print(f'A ordem decrescente é: {numero3} - {numero2}- {numero1} - {numero4}')

"""### 18. Faça um programa que receba quatro valores: I, A, B e C. Desses valores, I é inteiro e positivo, A, B e C são reais. Escreva os números A, B e C obedecendo à tabela a seguir.

*Suponha que o valor digitado para I seja sempre um valor válido, ou seja, 1, 2 ou 3, e que os números digitados sejam diferentes um do outro.*

  |VALOR DE I | FORMA A ESCREVER|
  |---|---|
  |1                  |A, B e C em ordem crescente.|
  |2                  |A, B e C em ordem decrescente|
  |3                  |O maior fica entre os outros dois números.|

  ```code
SE I == 1
    SE A<B E A<C
        SE B<C
            ESCREVA “A ordem crescente dos números é:”,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é:”,A,” -”,C,”-”,B
    SE B<A E B<C
        SE A<C
            ESCREVA “A ordem crescente dos números é:”,B,”-”,A,”-”,C
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,B,”-”,C,”-”,A
    SE C<A E C<B
        SE A<B
            ESCREVA “A ordem crescente dos números é: “,C,”-”,A,”-”,B
        SENÃO
            ESCREVA “A ordem crescente dos números é: “,C,”-”,B,”-”,A
SE I == 2
    SE A>B E A>C
        SE B>C
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,B,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,A,” -”,C,”-”,B
    SE B>A E B>C
        SE A>C
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,A,”-”,C
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,B,” -”,C,”-”,A
    SE C>A E C>B
        SE A>B
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,A,”-”,B
        SENÃO
            ESCREVA “A ordem decrescente dos números é: “,C,” -”,B,”-”,A
SE I == 3
    SE A>B E A>C
        ESCREVA “A ordem desejada é: “,B,”-”,A,”-”,C
    SE B>A E B>C
        ESCREVA “A ordem desejada é: “,A,”-”,B,”-”,C
    SE C>A E C>B
        ESCREVA “A ordem desejada é: “,A,”-”,C,”-”,B
```
"""

I = int(input('Digite um valor inteiro e positivo para I (1, 2 ou 3): '))
A = float(input('Digite o valor para A: '))
B = float(input('Digite o valor para B: '))
C = float(input('Digite o valor para C: '))
if I == 1:
    if A < B and A < C:
        if B < C:
            print(f'A ordem crescente dos números é: {A} - {B} - {C}')
        else:
            print(f'A ordem crescente dos números é: {A} - {C} - {B}')
    elif B < A and B < C:
        if A < C:
            print(f'A ordem crescente dos números é: {B} - {A} - {C}')
        else:
            print(f'A ordem crescente dos números é: {B} - {C} - {A}')
    elif C < A and C < B:
        if A < B:
            print(f'A ordem crescente dos números é: {C} - {A} - {B}')
        else:
            print(f'A ordem crescente dos números é: {C} - {B} - {A}')
elif I == 2:
    if A > B and A > C:
        if B > C:
            print(f'A ordem decrescente dos números é: {A} - {B} - {C}')
        else:
            print(f'A ordem decrescente dos números é: {A} - {C} - {B}')
    elif B > A and B > C:
        if A > C:
            print(f'A ordem decrescente dos números é: {B} - {A} - {C}')
        else:
            print(f'A ordem decrescente dos números é: {B} - {C} - {A}')
    elif C > A and C > B:
        if A > B:
            print(f'A ordem decrescente dos números é: {C} - {A} - {B}')
        else:
            print(f'A ordem decrescente dos números é: {C} - {B} - {A}')
elif I == 3:
    if A > B and A > C:
        print(f'A ordem desejada é: {B} - {A} - {C}')
    elif B > A and B > C:
        print(f'A ordem desejada é: {A} - {B} - {C}')
    elif C > A and C > B:
        print(f'A ordem desejada é: {A} - {C} - {B}')
else:
    print('Opção inválida para I. Deve ser 1, 2 ou 3.')
if A == B or A == C or B == C:
    print('Os números A, B e C tem que ser diferentes entre si.')

"""### 19. Faça um programa que mostre o menu de opções a seguir, receba a opção do usuário, número 1 para a escolha da soma, ou número 2 para a raiz quadrada, também receba os dados necessários para executar cada operação.

    Menu de opções:
    1. Somar dois números.
    2. Raiz quadrada de um número.

Observação: raiz = numero ** (1/2), ou
import math
raiz = math.sqrt(numero), assim como foi programado no exercício 18, da lista anterior.
      
"""

import math

print("Menu de opções:")
print("1. Somar dois números.")
print("2. Calcular a raiz quadrada de um número.")

escolha = input("Digite a opção desejada: ")

if escolha == '1':
    numero1 = float(input("Digite o primeiro número: "))
    numero2 = float(input("Digite o segundo número: "))
    resultado = numero1 + numero2
    print(f"A soma de {numero1} e {numero2} é igual a {resultado}.")
elif escolha == '2':
    numero = float(input("Digite um número para calcular a raiz quadrada: "))
    if numero >= 0:
        raiz_quadrada = math.sqrt(numero)
        print(f"A raiz quadrada de {numero} é igual a {raiz_quadrada:.2f}.")
    else:
        print("Inválido.")
else:
    print("Opção inválida. Por favor, digite 1 ou 2.")

"""### 20. Faça um programa que mostre a data e a hora do sistema nos seguintes formatos: **dia/mês/ano – mês por extenso e hora:minuto**.

**Observação: ***from*** carrega um módulo/biblioteca da linguagem Python e o ***import*** é usado para informar qual objeto desta biblioteca queremos importar/carregar no nosso programa. Se colocar apenas import será carregado tudo que tem dentro da biblioteca.**

    from datetime import datetime
    #Este comando obtem a data e hora de hoje de algum país onde esta o servidor que executa nosso programa feito no Collab, em Python.
    #Quando eu testei, o servidor era do fuso horário de Dakar-Senegal
    hoje = datetime.now()
    print ('Ano atual.:',hoje.year)
    print ('Mês.......:',hoje.month)
    print ('Dia.......:',hoje.day)
    print ('Hora......:',hoje.hour)
    print ('Minuto....:',hoje.minute)
    print ('Segundos..:',hoje.second)
"""

from datetime import datetime
hoje = datetime.now()
print ('Ano atual.:',hoje.year)
print ('Mês.......:',hoje.month)
print ('Dia.......:',hoje.day)
print ('Hora......:',hoje.hour)
print ('Minuto....:',hoje.minute)
print ('Segundos..:',hoje.second)
if hoje.month == 1:
    print(hoje.day,'/Janeiro/',hoje.year)
elif hoje.month == 3:
     print(hoje.day,'/Março/',hoje.year)
elif hoje.month == 4:
    print(hoje.day,'/Maio/',hoje.year)
elif hoje.month == 5:
     print(hoje.day,'/junho/',hoje.year)
elif hoje.month == 6:
     print(hoje.day,'/julho/',hoje.year)
elif hoje.month == 7:
     print(hoje.day,'/Agosto/',hoje.year)
elif hoje.month ==8:
     print(hoje.day,'/Setembro/',hoje.year)
elif hoje.month == 9:
     print(hoje.day,'/Outubro/',hoje.year)
elif hoje.month == 10:
     print(hoje.day,'/novembro/',hoje.year)
elif hoje.month ==11:
     print(hoje.day,'/Setembro/',hoje.year)
elif hoje.month ==12:
     print(hoje.day,'/Dezembro/',hoje.year)
else:
    print('Invalido')

# DICA-curiosidade, o trecho de código a
# seguir, mostra como trocar o fuso
# horário para o país que deseja, no caso Brasil
###################################################
# datetime nome do arquivo onde contém as
# classes/funções (datetime, timezone, timedelta)
# que eu desejo usar, neste exemplo
# datetime, timezone, timedelta
###################################################
from datetime import datetime, timezone, timedelta

data_e_hora_atuais = datetime.now()
fuso_horario = timezone(timedelta(hours=-3))
print('UTC - Tempo Universal Coordenado:', fuso_horario)
data_e_hora_SP = data_e_hora_atuais.astimezone(fuso_horario)
data_e_hora_SP_em_texto = data_e_hora_SP.strftime('%d/%m/%Y %H:%M')
print('Data e horário de São Paulo:',data_e_hora_SP_em_texto)

"""### 21. Faça um programa que determine a data cronologicamente maior entre duas datas fornecidas pelo usuário. Cada data deve ser composta por três valores inteiros, em que o primeiro representa o dia, o segundo, o mês e o terceiro, o ano.

  ```code
  SE ano1 > ano2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE ano2>ano1
      ESCREVA “A maior data é: “,dia2,”-”,mes2,”-”,ano2
  SENÃO SE mes1>mes2
      ESCREVA “A maior data é: “,dia1,”-”,mes1,”-”,ano1
  SENÃO SE mes2>mes1
      ESCREVA “A maior data é: “,dia2, “-”,mes2,”-”,ano2
  SENÃO SE dia1>dia2
      ESCREVA “A maior data é: “-”,dia1,”-”,mia1,” -”,ano1
  SENÃO SE dia2>dia1
      ESCREVA “A maior data é: “,dia2,” -”,mes2,”-”,ano2
  SENÃO
      ESCREVA “As datas são iguais!”
  ```
"""

# Digite seu código aqui

"""### 22. Faça um programa que receba a hora do início de um jogo e a hora do término (cada hora é composta por duas variáveis inteiras: hora e minuto). Calcule e mostre a duração do jogo (horas e minutos), sabendo que o tempo máximo de duração do jogo é de 24 horas e que ele pode começar em um dia e terminar no dia seguinte.
    SE min_inicial > min_f
        min_final = min_final + 60
        hora_final = hora_final – 1
    SE hora_inicial > hora_final
        hora_final = hora_final + 24
    minuto_duracao = min_final - min_inicial
    hora_duracao = hora_final - hora_inicial
"""

# Digite seu código aqui

"""### 23. Faça um programa que receba o código correspondente ao cargo de um funcionário e seu salário atual e mostre o cargo, o valor do aumento e seu novo salário. Os cargos estão na tabela a seguir.

  |CÓDIGO|CARGO|PERCENTUAL|
  |---|---|---|
  |1|Escriturário|50%|
  |2|Secretário|35%|
  |3|Caixa|20%|
  |4|Gerente|10%|
  |5|Diretor|Não tem aumento|

```code
SE cargo == 1
    ESCREVA “O cargo é Escriturário”
    aumento = salario * 50 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 2
    ESCREVA “O cargo é Secretário”
    aumento = salario * 35 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal]
SENÃO SE cargo == 3
    ESCREVA “O cargo é Caixa”
    aumento = salario * 20 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “,novo_sal
SENÃO SE cargo == 4
    ESCREVA “O cargo é Gerente”
    aumento = salario * 10 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
SENÃO SE cargo == 5
    ESCREVA “O cargo é Diretor”
    aumento = salario * 0 / 100
    ESCREVA “O valor do aumento é: “, aumento
    novo_sal = salario + aumento
    ESCREVA “O novo salário é: “, novo_sal
```
"""

# Digite seu código aqui

"""### 24. Faça um programa que apresente o menu a seguir, permita ao usuário escolher a opção desejada, receba os dados necessários para executar a operação e mostre o resultado. Verifique a possibilidade de opção inválida e não se preocupe com restrições, como salário negativo.

    Menu de opções
    1. Imposto
    2. Novo salário
    3. Classificação
    Digite a opção desejada:

*Na opção 1: receber o salário de um funcionário, calcular e mostrar o valor do imposto usando as regras a seguir.*

  |SALÁRIO|PERCENTUAL DO IMPOSTO|
  |---|---|
  |Menor que  500,00|5%|
  |De  500,00 (inclusive) a  850,00 (inclusive)|10%|
  |Acima de  850,00|15%|

*Na opção 2: receber o salário de um funcionário, calcular e mostrar o valor do novo salário, usando as regras a seguir.*

  |SALÁRIO|AUMENTO|
  |---|---|
  |Maior que  1.500,00| 25,00|
  |De  750,01 a  1.500,00 (inclusive)| 50,00|
  |De  450,00 (inclusive) a  750,00| 75,00|
  |Menor que  450,00| 100,00|

*Na opção 3: receber o salário de um funcionário e mostrar sua classificação usando a tabela a seguir.*

|SALÁRIO|CLASSIFICAÇÃO|
|---|---|
|Até  700,00 (inclusive)|Mal remunerado|
|Maiores que  700,00|Bem remunerado|

"""

# Digite seu código aqui

"""###25. Faça um programa que receba o salário inicial de um funcionário, calcule e mostre o novo salário, acrescido de bonificação e de auxílio escola.

|SALÁRIO|BONIFICAÇÃO|
|---|---|
|Até  500,00|5% do salário|
|Entre  500,01 e 1.200,00|12% do salário|
|Acima de  1.200,00|Sem bonificação|
>
|SALÁRIO|AUXÍLIO ESCOLA|
|---|---|
|Até  600,00| 150,00|
|Acima de  600,00| 100,00|

novo_salario = salario + bonificacao + auxílio escola
"""

# Digite seu código aqui

"""### 26. Faça um programa que receba o valor do salário mínimo, o número de horas trabalhadas, o número de dependentes do funcionário e a quantidade de horas extras trabalhadas. Calcule e mostre o salário a receber do funcionário de acordo com as regras a seguir:

  * O valor da hora trabalhada é igual a 1/5 do salário mínimo.
  * O salário do mês é igual ao número de horas trabalhadas multiplicado pelo valor da hora trabalhada.
  * Para cada dependente, acrescentar  32,00.
  * Para cada hora extra trabalhada, calcular o valor da hora * trabalhada acrescida de 50%.
  * O salário bruto é igual ao salário do mês mais o valor dos dependentes mais o valor das horas extras.
  * Calcular o valor do impostoosto de renda retido na fonte de acordo com a tabela a seguir:

|IRFF|SALÁRIO BRUTO|
|---|---|
|Isento|Inferior a  200,00|
|10%|De  200,00 até 500,00|
|20%|Superior a  500,00|

  * O salário líquido é igual ao salário bruto menos IRRF.
  * A gratificação é de acordo com a tabela a seguir:

|SALÁRIO LÍQUIDO|GRATIFICAÇÃO|
|---|---|
|Até 350,00| 100,00|
|Superior a  350| 50,00|

  * O salário a receber do funcionário é igual ao salário líquido mais a gratificação.

  ```code
  LEIA salario_minimo, numero_horas_trabalhadas, numero_dependentes, numero_horas_extras
  
  valor_hora = 1/5 * salario_minimo
  salario_mes = numero_horas_trabalhadas * valor_hora
  valor_dependentes = 32 * numero_dependentes
  valor_hora_extra = numero_horas_extras * (valor_hora + (valor_hora * 50/100))
  salario_bruto =salario_mes + valor_dependentes + valor_hora_extra
  
  SE salario_bruto < 200
        imposto = 0
  SENÃO SE salario_bruto >= 200 E salario_bruto <= 500
        imposto = salario_bruto * 10/100
  SENÃO SE salario_bruto > 500
        imposto = salario_bruto * 20/100
  salario_liquido = salario_bruto – imposto
  SE salario_liquido <= 350
        gratificacao = 100
  SENÃO
        gratificacao = 50
  salario_a_receber = salario_liquido + gratificacao
  
  ESCREVA salario_a_receber
  ```
"""

# Digite seu código aqui

"""### 27 Um supermercado deseja reajustar os preços de seus produtos usando o seguinte critério: o produto poderá ter seu preço aumentado ou diminuído. Para o preço ser alterado, o produto deve preencher pelo menos um dos requisitos a seguir:

|VENDA MÉDIA MENSAL|PREÇO ATUAL|% DE AUMENTO|% DE DIMINUIÇÃO|
|---|--|---|---|
|< 500|<  30000|10|-|
|\>= 500 e <1200|\>=  30.00 e <  80.00|15|-|
|\>= 1200|\>=  80.00|-|20|

* Faça um programa que receba o preço atual e a venda média mensal do produto, calcule e mostre o novo preço.

```code
LEIA preco_atual, media_mensal_vendas

SE media_mensal_vendas < 500 OU preco_atual < 30
    novo_preco = preco_atual + 10/100 * preco_atual
SENÃO SE media_mensal_vendas >= 500 E media_mensal_vendas < 1200 OU preco_atual >= 30 E preco_atual<80
    novo_preco = preco_atual + 15 / 100 * preco_atual
SENÃO SE venda >= 1200 OU preco_atual >= 80
    novo_preco = preco_atual – 20 / 100 * preco_atual
      
ESCREVA novo_preco
```
"""

# Digite seu código aqui

"""### 28. Faça um programa para resolver equações do 2 o grau.

**ax² + bx + c = 0**

A variável *a* deve ser diferente de zero*

  * delta = b ** 2 - 4 * a * c
  * delta < 0.  **Não existe raiz real**
  * delta = 0. **Existe uma raiz real**
    * x = (-b) / (2 * a)
  * delta > 0. **Existem duas raízes reais**
    * x1 = -b + raiz(delta)/ (2 * a)
    * x2 = -b  - raiz(delta)/ (2 * a)

```code
LEIA a, b, c
SE a = 0
    ESCREVA “Estes valores não formam uma equação de segundo grau”
SENÃO
    delta = (b * b) – ( 4 * a * c)
    SE delta < 0
        ESCREVA “Não existe raiz real”
    SE delta = 0
        ESCREVA “Existe uma raiz real”
        x1 = (– b) / (2 * a)
        ESCREVA x1
    SE delta > 0
        ESCREVA “Existem duas raízes reais”
        x1 = (– b) + raiz(delta) / (2 * a)
        x2 = (– b) - raiz(delta) / (2 * a)
        ESCREVA(x1, x2)
```
"""

# Digite seu código aqui

"""### 29. Dados três valores X, Y e Z, verifique se eles podem ser os comprimentos dos lados de um triângulo e, se forem, verifique se é um triângulo equilátero, isósceles ou escaleno. Se eles não formarem um triângulo, escreva uma mensagem.
Considere que:
* o comprimento de cada lado de um triângulo é menor que a soma dos outros dois lados;
* chama-se equilátero o triângulo que tem três lados iguais;
* denomina-se isósceles o triângulo que tem o comprimento de dois lados iguais;
* recebe o nome de escaleno o triângulo que tem os três lados diferentes.

```code
LEIA x, y, z
SE x < y + z E y < x + z E z < x + y
    SE x = y E y = z
        ESCREVA “Triângulo Equilátero”
    SENÃO SE x = y OU x = z OU y = z
        ESCREVA “Triângulo Isósceles”
    SENÃO SE x ≠ y E x ≠ z E y ≠ z
        ESCREVA “Triângulo Escaleno”
SENÃO
    ESCREVA “Essas medidas não formam um triângulo”
```
"""

# Digite seu código aqui

"""### 30. Faça um programa que receba a altura e peso de uma pessoa. De acordo com a tabela a seguir, verifique e mostre a classificação dessa pessoa.

|ALTURA|ATÉ 60|ENTRE 60 E 90 (INCLUSIVE)|ACIMA DE 90|
|---|---|---|---|
|Menores que 1,20|A|D|G|
|De 1,20 a 1,70|B|E|H|
|Maiores que 1,70|C|F|I|

```code
LEIA altura, peso
SE altura < 1.20
    SE peso <= 60
        ESCREVA “A”
    SENÃO SE peso > 60 E peso <= 90
        ESCREVA “D”
    SENÃO SE peso > 90
        ESCREVA “G”
SENÃO SE altura >= 1.20 E altura <= 1.70
    SE peso <= 60
        ESCREVA “B”
    SENÃO SE peso > 60 E peso <= 90
        ESCREVA “E”
    SENÃO SE peso > 90
        ESCREVA “H”
SENÃO SE altura > 1.70
    SE peso <= 60
        ESCREVA “C”
    SENÃO SE peso > 60 E peso <= 90
        EESCREVA “F”
    SENÃO SE peso > 90
        ESCREVA “I”
```
"""

# Digite seu código aqui

"""### 31. Faça um programa que receba:

* O código de um produto comprado, supondo que a digitação do código do produto seja sempre válida, isto é, um número * inteiro entre 1 e 10.
* O peso do produto em quilos.
* O código do país de origem, supondo que a digitação do  código seja sempre válida, isto é, um número inteiro entre 1 e 3.

|CÓDIGO DO PAÍS DE ORIGEM|IMPOSTO|
|---|---|
|1|0%|
|2|15%|
|3|25%|

|CÓDIGO DO PAÍS DO PRODUTO|PREÇO POR GRAMA|
|---|---|
|1 a 4|10|
|5 a 7|25|
|8 a 10|35|

Calcule e mostre:
* o peso do produto convertido em gramas;
* o preço total do produto comprado;
* valor do imposto, sabendo que ele é cobrado sobre o * preço total do produto comprado e dependendo país de origem;
* o valor total, preço total do produto mais imposto.

```code
LEIA codigo_produto, peso_quilos, codigo_pais
peso_em_gramas = peso_quilos * 1000
ESCREVA peso_em_gramas
SE codigo_produto >= 1 E codigo_produto <= 4
   preco_por_grama = 10
SENÃO SE codigo_produto >= 5 E codigo_produto <= 7
   preco_por_grama = 25
SENÃO SE codigo_produto >= 8 E codigo_produto <= 10
   preco_por_grama = 35    
preco_total = peso_em_gramas *preco_por_grama
ESCREVA preco_total
SE codigo_pais = 1
    imposto = 0
SENÃO SE codigo_pais = 2
    imposto = preco_total * 15/100
SENÃO SE codigo_pais = 3
    imposto = preco_total * 25/100    
ESCREVA imposto
valor_total = preco_total + imposto
ESCREVA valor_total
```
"""

# Digite seu código aqui

"""### 32. Faça um programa que receba:
* o código do estado de origem da carga de um caminhão, supondo que a digitação do código do estado seja sempre válida, isto é, um número inteiro entre 1 e 5;
* o peso da carga do caminhão em toneladas;
* o código da carga, supondo que a digitação do código seja sempre válida, isto é, um número inteiro entre 10 e 40.

| CÓDIGO DO ESTADO| IMPOSTO|
|---|---|
|1|35%|
|2|25%|
|3|15%|
|4|5%|
|5|Isento|
>
CÓDIGO DA CARGA|PREÇO POR QUILO
---|---
10 a 20|100
21 a 30|250
31 a 40|400

Calcule e mostre:
* o peso da carga do caminhão convertido em quilos;
* o preço da carga do caminhão;
* o valor do imposto, sabendo que o imposto é cobrado sobre o preço da carga do caminhão e depende do estado de origem;
* o valor total transportado pelo caminhão, preço da carga mais imposto.

```
LEIA codigo_estado, peso_em_toneladas, codigo_carga
peso_em_quilos = peso_em_toneladas * 1000
ESCREVA peso_em_quilos
SE codigo_carga >= 10 E codigo_carga <= 20
    preco_da_carga = 100 * peso_em_quilos
SENÃO SE codigo_carga >= 21 E codigo_carga <= 30
    preco_da_carga = 250 * peso_em_quilos
SENÃO SE codigo_carga >= 31 E codigo_carga <= 40
    preco_da_carga = 340 * peso_em_quilos   
ESCREVA preco_da_carga
SE codigo_estado = 1
    imposto = 35/100 * preco_da_carga
SENÃO SE codigo_estado = 2
    imposto = 25/100 * preco_da_carga
SENÃO SE codigo_estado = 3
    imposto = 15/100 * preco_ds_carga
SENÃO SE codigo_estado = 4
    imposto = 5/100 * preco_da_carga
SENÃO SE codigo_estado = 5
    imposto = 0
ESCREVA imposto
valor_total = preco_da_carga + imposto
ESCREVA valor_total
```
"""

# Digite seu código aqui

"""### 33. Faça um programa que receba o salário base e o tempo de serviço de um funcionário. Calcule e mostre:
* O imposto, conforme a tabela a seguir.

|SALÁRIO BASE|% SOBRE O SALÁRIO BASE|
|---|---|
|< 200|isento|
|>= 250 E <= 450|3%|
|>  450 E < 700|8%|
|>=  700|12%|

* A gratificação, de acordo com a tabela a seguir.

SALÁRIO BASE R$|TEMPO DE SERVIÇO|GRATIFICAÇÃO
---|---|---
Superior a 500,00|Até 3 anos|20
 | Mais de 3 anos|30
  --------------------------|---------|--------------
Até 500,00|Até 3 anos|23
|Entre 3 e 6 anos|35
|Acima de 6 anos|33

* O salário líquido, ou seja, salário base menos imposto mais gratificação.
* A categoria, que está na tabela a seguir.

```
LEIA salario_base, tempo

SE salario_base < 200
    imposto = 0
SENÃO SE salario_base <= 450
    imposto = 3/100 * salario_base
SENÃO SE sal_base < 700
    imposto = 8/100 * salario_base
SENÃO
    imposto = 12/100 * salario_base
ESCREVA imposto
SE salario_base > 500
    SE tempo <= 3
         gratificacao = 20
    SENÃO
        gratificacao = 30
SENÃO
    SE tempo <= 3
        gratificacao = 23
    SENÃO SE tempo < 6
        gratificacao = 35
    SENÃO gratificacao = 33
ESCREVA gratificacao
salario_liquido = salario_base – imposto + gratificacao
ESCREVA salario_liqquido
SE salario_liquido <= 350
    ESCREVA “Classificação A”
SENÃO SE salario_liqquido < 600
    ESCREVA “Classificação B”
SENÃO
    ESCREVA “Classificação C”
```
"""

# Digite seu código aqui

"""### 34. Faça um programa que:
* receba o valor do salário mínimo,
* o turno de trabalho (M — matutino; V — vespertino; ou N — noturno),
* a categoria (O — operário; G — gerente)
* número de horas trabalhadas no mês de um funcionário.

*Suponha a digitação apenas de dados válidos e, quando houver digitação de letras, utilize maiúsculas.*

**Calcule e mostre:**

* O coeficiente do salário, de acordo com a tabela a seguir.

TURNO DE TRABALHO|VALOR DO COEFICIENTE
---|---
M - Matutino|10% do salário mínimo
V - Vespertino|15% do salário mínimo
N - Noturno|20% do salário mínimo

* O valor do salário bruto, ou seja, o número de horas trabalhadas multiplicado pelo valor do coeficiente do salário.

* O imposto, de acordo com a tabela a seguir.

CATEGORIA| SALÁRIO BRUTO|IMPOSTO SOBRE O SALÁRIO BRUTO
---|---|---
O - Operário|>= 300,00|5%
O - Operário|< 300,00|3%
G - Gerente|>= 300,00|6%
G - Gerente|< 300,00|4%

* A gratificação, de acordo com as regras a seguir. Se o funcionário preencher todos os requisitos a seguir, sua gratificação será de 50,00; caso contrário, será de 30,00. Os requisitos são:
 * Turno: Noturno
  * Número de horas trabalhadas: Superior a 80 horas
  * O auxílio alimentação, de acordo com as seguintes regras.
* Auxilio alimentação, um terço do seu salário bruto; caso contrário, será de metade do seu salário bruto. Os requisitos são:
  * Se o funcionário preencher algum dos requisitos a seguir, seu auxílio alimentação será de
  * Categoria: Operário
  * Coeficiente do salário: < = 25
* O salário líquido, ou seja, salário bruto menos imposto mais gratificação mais auxílio alimentação.
* A classificação, de acordo com a tabela a seguir:

SALÁRIO LÍQUIDO|MENSAGEM
---|---
Menor que 350,00|Mal remunerado
Entre 350 e 600,00|Normal
Maior que 600,00|Bem remunerado

```
LEIA salario_minino, turno, categoria, numero_de_horas_trabalhadas
SE turno = “M”
     coeficiente = 10/100 * salario_minino
SENÃO SE turno = “V”
     coeficiente = 15/100 * salario_minino
SENÃO SE turno = “N”
     coeficiente = 12/100 * salario_minino
     
ESCREVA coeficiente

salario_bruto = numero_de_horas_trabalhadas * coeficiente

ESCREVA salario_bruto

SE categoria = “O”
    SE sal_bruto >= 300
        imposto = 5/100 * sal_bruto
    SENÃO
        imposto = 3/100 * sal_bruto
SENÃO
    SE salario_bruto >= 400
        imposto = 6/100 * salario_bruto
    SENÃO
         imposto = 4/100 * salario_bruto
         
ESCREVA imposto

SE turno = “N” E numero_de_horas_trabalhadas > 80
    gratificacao = 50
SENÃO
    gratificacao = 30
    
ESCREVA gratificacao

SE categoria = “O” OU coeficiente <= 25
    auxilio = 1/3 * salario_bruto
SENÃO
    auxilio = 1/2 * salario_bruto
    
ESCREVA auxilio

salario_liquido = salario_bruto – imposto + gratificacao + auxilio

ESCREVA salario_liquido

SE salario_liquido < 350
     ESCREVA “Mal Remunerado”
SENÃO SE salario_liquido >= 350 E salario_liqquido <= 600
     ESCREVA “Normal”
SENÃO SE salario_liquido > 600
     ESCREVA “Bem Remunerado”
```
"""

# Digite seu código aqui

"""### 35. Faça um programa que receba de um produto:
* o preço
* o tipo (A — alimentação; L — limpeza; e V — vestuário)
* a refrigeração (S — produto que necessita de refrigeração; e N — produto que não necessita de refrigeração) .

**Suponha que haverá apenas a digitação de dados válidos e, quando houver digitação de letras, utilize maiúsculas. Calcule e mostre:**

* O valor adicional, de acordo com a tabela a seguir:

REFRIGERAÇÃO|TIPO|PREÇO|VALOR ADICIONAL
---|---|---|---
N|A|<  15,00|2,00|
 | |>= 15,00|5,00|
 |---------|--------------|-------------------------------
 |L|< 10,00|1,50
 | |>= 10,00|2,50
  |---------|--------------|-------------------------------
 |V|< 30,00|3,00
 ||>= 30,00|2,50
  --------------------------|---------|--------------|-------------------------------
S|A||8,00
|L||0,00
|V||0,00

* O valor do imposto, de acordo com a regra a seguir.

PREÇO|PERCENTUAL SOBRE O PREÇO
---|---
< 25,00|5%
>= 25,00|8%

O preço de custo, ou seja, preço mais imposto.
O desconto, de acordo com a regra a seguir.

O produto que não preencher nenhum dos requisitos a seguir terá desconto de 3%, caso contrário, 0 (zero). Os requisitos são:
* Tipo: A
* Refrigeração: S

* O novo preço, ou seja, preço de custo mais adicional menos desconto.
* A classificação, de acordo com a regra a seguir.

NOVO PREÇO|CLASSIFICAÇÃO
---|---
<= 50,00|Barato
Entre 50,01 e 100,00|Normal
>= 100,00|Caro


```
LEIA pre, tipo, refrig
SE refrig = “N”
    SE tipo = “A”
        SE pre < 15
           valor_adic = 2
        SENÃO
           valor_adic = 5
    SE tipo = “L”
        SE pre < 10
           valor_adic = 1.5
        SENÃO
           valor_adic = 2.5
    SE tipo = “V”
        SE pre < 30
           valor_adic = 3
        SENÃO
           valor_adic = 2.5
SENÃO SE tipo = “A”
    valor_adic = 8
    SE tipo = “L”
        valor_adic = 0
    SE tipo = “V”
        valor_adic = 0
ESCREVA valor_adic
SE pre < 25
    imposto = 5/100 * pré
SENÃO
    imposto = 8/100 * pre
ESCREVA imposto
pre_custo = pre + imposto
ESCREVA pre_custo
SE tipo != “A” E refrig != “S”
  desconto = 3/100 * pre_custo
SENÃO
  desconto = 0
ESCREVA desconto
novo_pre = pre_custo + valor_adic – desconto
ESCREVA novo_pre
SE novo_pre <= 50
    ESCREVA “Barato”
SENÃO SE novo_pre < 100
    ESCREVA “Normal”
SENÃO
    ESCREVA “Caro”

"""

# Digite seu código aqui

"""### 36. Faça um programa que receba a medida de um ângulo em graus. Calcule e mostre o quadrante em que se localiza esse ângulo. Considere os quadrantes da trigonometria e, para ângulos maiores que 360° ou menores que −360°, reduzí-los, mostrando também o número de voltas e o sentido da volta (horário ou anti-horário).
```
SE angulo > 360 OU angulo < -360
    voltas = parte inteira(angulo / 360)    
    angulo = RESTO(angulo / 360)
SENÃO
    voltas = 0
SE angulo = 0 OU angulo = 90 OU angulo = 180
           OU angulo = 270 OU angulo = 360
           OU angulo = -90 OU angulo = -180
           OU angulo = -270 OU angulo = -360
  ESCREVA “Está em cima de algum dos eixos”
  SE (angulo > 0 E angulo < 90) OU (angulo < -270 E angulo > -360)
    ESCREVA “1o Quadrante”
  SENÃO SE (angulo > 90 E angulo < 180) OU (angulo < -180 E angulo > -270)
    ESCREVA “2o Quadrante”
  SENÃO SE (angulo > 180 E angulo < 270) OU (angulo < -90 E angulo > -180)
    ESCREVA “3o Quadrante”
  SENÃO SE (angulo > 270 E angulo < 360) OU (angulo < 0 E angulo > -90)
    ESCREVA “4o Quadrante”
  ESCREVA voltas, “ volta(s) no sentido “
SE angulo < 0
    ESCREVA “horário”
SENÃO
    ESCREVA “anti-horário”
```
"""

# Digite seu código aqui