# -*- coding: utf-8 -*-
"""Flaviana Gomes - 232_Est_Repeticao_m.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xaKvSRnRvK2MjqGgrgsU1P9O2JTfa_qa

#ESTRUTURA DE REPETIÇÃO -> 1 a 13 - o restante fica para estudo
##Todos estes algoritmos/programas podem ser implementados com o comando **while** ou **for**. Para estudar, implemente cada exercício com as **duas** estruturas de repetição.

###1. Faça um algoritmo  que mostre 10 vezes a frase “Bem vindo a Fatec!”. Pode implementar com o comando while ou for.
"""

print('Exemplo do while.............\n\n')
# 1º passo - inicialização
contador = 1
# 2º passo - condição/critério de parada
while contador <= 5:
    print(contador, 'Bem vindo a Fatec!')
    contador = contador + 1 # 3º passo - incremento
print('\n\nFim\t................')

for contador in range(8): #range < 8
    print(contador,'Bem vindo a Fatec!')

"""###2. Faça um algoritmo que mostre o cumprimento ‘Olá ‘ para o nome de alguém (4 pessoas). Exemplo ‘Olá Mariana’. Pode implementar com o comando while ou for.

"""

pessoas = 0
while pessoas < 4:
    nome = input('Digite o nome ')
    print('Olá',nome,' tudo bem?')
    pessoas = pessoas + 1

for pessoas in range(4):
    nome = input('Digite o nome ')
    print('Olá',nome,' tudo bem?')

nome1 = input('Digite o nome ')
print('Olá',nome1,' tudo bem?')
nome2 = input('Digite o nome ')
print('Olá',nome2,' tudo bem?')
nome3 = input('Digite o nome ')
print('Olá',nome3,' tudo bem?')
nome4 = input('Digite o nome ')
print('Olá',nome4,' tudo bem?')

"""###3. Faça um algoritmo que mostre os valores de 0 a 15. Pode implementar com o comando while ou for.

"""

for contador in range (16):
    print(contador)

numero = 0
while numero < 16:
    print(numero)
    numero += 1

"""###4. Faça um algoritmo que mostre os valores de 3 a 20. Pode implementar com o comando while ou for.

"""

for contador in range (3,21):
    print(contador)

numero = 3
while numero < 21:
    print(numero)
    numero += 1

"""###5. Faça um algoritmo que calcule e mostre a tabuada do 5. Pode implementar com o comando while ou for.

"""

numero = 0
while numero <=10:
    tabuada = 5 * numero
    print(f"5 x {numero} = {tabuada}")
    numero = numero + 1

"""###6. Faça um algoritmo que receba a idade de 10 pessoas, calcule e exiba a quantidade de pessoas maiores de idade, sendo que a maioridade é obtida após completar 18 anos. Pode implementar com o comando while ou for.

"""

pessoas = 1
contador = 0
while pessoas <= 10:
    idade = int(input("Digite a sua idade: "))
    if idade >= 18:
        contador = contador + 1
    pessoas = pessoas + 1
print ("Quantidade de pessoas > de 18 anos", contador)

contador = 0
for cont in range(1,11):
    idade = int(input("Digite a idade: "))
    if idade >=18:
        contador = contador + 1
print ("A quantidade de pessoas com mais de 18 anos é", contador)

"""###7. Escreva um algoritmo que receba 23 números, calcule e exiba a quantidade de números pares e impares. Pode implementar com o comando while ou for.

"""

contador_par = 0
contador_impar = 0
contador = 0
while contador < 23:
    numero = int(input("Digite um número: "))
    if numero % 2 == 0:
        contador_par = contador_par + 1
    else:
        contador_impar = contador_impar + 1
    contador += 1
print(f"Há {contador_par} números pares e {contador_impar} números ímpares")

contador_par = 0
contador_impar = 0
for cont in range (1,24):
    numero = int(input("Digite um número: "))
    if numero % 2 == 0:
        contador_par = contador_par + 1
    else:
        contador_impar = contador_impar + 1
print(f"Há {contador_par} números pares e {contador_impar} números ímpares ")

"""###8. Faça um algoritmo que calcule e exiba o salário reajustado de dez funcionários de acordo com a seguinte regra (pode implementar com o comando while ou for):
## Salário até 300, reajuste de 50%;

##Salários maiores que 300, reajuste de 30%.



"""

contador = 1
while contador <=10:
    salario = float(input("Digite o seu salário: "))
    contador +=1
    if salario <=300:
        salario_novo = salario + (salario  * 50/100)
    else:
        salario_novo = salario + (salario * 30/100)
    print(f"Seu novo salário é: {salario_novo:.2f}")

contador = 0
for cont in range(1,11):
    salario = float(input("Digite o salário: "))
    if salario < 300:
        salario_novo = salario + (salario * 50/100)

    else:
        salario_novo = salario + (salario * 30/100)
    print(f"Seu novo salário é {salario_novo:.2f}")

"""
###9. Faça um algoritmo que conheça 4 preços de produtos, some-os e mostre o resultado. Pode implementar com o comando while ou for.
"""

soma_preco = 0
for cont in range(1,5):
    preco = float(input("Digite o preço: "))
    soma_preco = soma_preco + preco
print(f"A soma dos preços é: {soma_preco:.2f}")

contador = 1
soma_preco = 0
while contador < 5:
    preco = float(input("Digite o preço: "))
    soma_preco = soma_preco + preco
    contador = contador + 1
print(f"A soma dos produtos é: {soma_preco:.2f}")

"""###10. Faça um algoritmo que conheça 4 preços de produtos, calcule e mostre a média aritmética dos preços. Pode implementar com o comando while ou for.

"""

soma_precos = 0
contador = 0
while contador < 4:
    preco = float(input("Digite o preço do produto: R$ "))
    soma_precos += preco
    contador += 1
media = soma_precos / 4
print(f"A média dos preços dos produtos é de R${media:.2f}")

somaid = 0
for cont in range (1,5):
    preco = int(input("Digite o preço aqui: "))
    somaid = somaid + preco
media = somaid / 4
print(f'A média dos preços é {media:.2f}')

"""###11. Faça um algoritmo que calcule e informe a média de idades de 5 alunos. Pode implementar com o comando while ou for."""

somaid = 0
for cont in range (1,6):
    idade = int(input("Digite a sua idade aqui: "))
    somaid = somaid + idade
media = somaid / 5
print(f'A média dos preços é {media:}')

somaid = 0
contador = 0
while contador < 5:
    idade = int(input("Digite a sua idade: "))
    somaid += idade
    contador += 1
media = somaid / 5
print(f"A média das idades inseridas é de {media}")

"""###12. Faça um programa que receba a idade e a altura de 20 pessoas. Calcule e exiba a média das alturas das pessoas com mais de 20 anos.



"""

soma_alturas = 0
contador = 0
for cont in range(2):
        idade = int(input(f"Digite a idade da pessoa: "))
        altura = float(input(f"Digite a altura da pessoa (em metros): "))
if idade > 20:
            soma_alturas += altura
            contador += 1
if contador > 0:
    media_alturas = soma_alturas / contador
    print(f"A média das alturas das pessoas com mais de 20 anos é: {media_alturas:.2f} metros")
else:
    print("Nenhuma pessoa com mais de 20 anos foi inserida.")

"""###13. Faça um algoritmo que leia o preço de 20 TV, determine e apresente a média dos preços que possuem valor maior que R$ 1000. Pode implementar com o comando while ou for."""

tv = 1
preco_total = 0
conta_tv = 0
while tv <= 20:
  preco_tv = float(input("Digite o preço da TV: "))
  if preco_tv >= 1000:
    preco_total = preco_total + preco_tv
    conta_tv = conta_tv+1
  tv = tv+1
media_preco = preco_total/conta_tv
print(f"A média dos preços das tvs com o valor maior de R$1000 é R${media_preco:.2f}")

"""###14. Faça um programa que receba a altura e nome  de 5 pessoas. Encontre e apresente a altura da pessoa mais alta e da mais baixa e seus respectivos nomes."""

# Digite seu código aqui

"""###15. Faça um programa que receba dez valores inteiros, encontre e apresente o maior e o menor valor.


"""

# Digite seu código aqui

"""###16. Os alunos do primeiro módulo farão a P1 da disciplina de Algoritmo. Crie um algoritmo que leia as 40 notas e RAs, encontre e apresente a maior, a menor e os respectivos RAs desses alunos."""

# Digite seu código aqui

"""###17. Faça um programa que calcule e apresente as tabuadas do 3 ao 7. Este exercício utiliza DUAS estruturas de repetição."""

# Digite seu código aqui

"""###18. Faça um programa para o curso de ADS (6 módulos), cada sala tem 30 alunos, calcule e apresente os seguintes itens:
*  Quantidade de homens e mulheres de cada módulo;
*  Média de idades de cada módulo;
*  Quantidade de homens e mulheres do curso todo;
*  Média de idades do curso todo.

Observação: este exercício utiliza DUAS estruturas de repetição.
"""

for modulo in range(1,7):
    print(modulo,'º módulo','.'*50)
    # contar genero feminino = 0
    for alunos in range(1,3):
        # digitar os dados dos alunos
        genero = input('Cadastre o gênero M/F: ')
        if genero == 'F' or genero == 'f':
            # contar genero feminino
        #...
    # mostrar resultados de cada módulo
    # acumular valores para o curso
# mostrar resultados do curso